<style>
p {
	margin: 0;
	text-indent: 15pt;
	text-align: justify;
}
</style>
<p align=center style='text-align: center'><b>ПОРТАЛ ОАО «ЕВРАЗКЛИМАТ»</b></p>
<br />
<p>Корпоративный портал планирования и реализации инженерных проектов
ОАО «ЕВРАЗКЛИМАТ» (далее – Портал) предназначен для оптимизации
управления проектами и бизнес-процессами в рамках аудитории ОАО
«ЕВРАЗКЛИМАТ».</p>
<br/><br/>
<p align=center style='text-align: center'><b>Контактная информация:</b></p><br/>
<b>Адрес:</b> 115088, г. Москва, ул. Угрешская, д. 2, стр. 52<br/>
<b>Тел./факс:</b> +7 495 988 9296<br/>
<b>E-mail:</b> <a href="mailto:info@eurasmail.ru">info@eurasmail.ru</a>