<p class=MsoNoSpacing align=center style='text-align:center'><b
style='mso-bidi-font-weight:normal'><span style='font-size:16.0pt;font-family:
"Arial","sans-serif"'>ПОРТАЛ ОАО «ЕВРАЗКЛИМАТ»<o:p></o:p></span></b></p>

<p class=MsoNoSpacing align=center style='text-align:center'><b
style='mso-bidi-font-weight:normal'><span style='font-size:14.0pt;font-family:
"Arial","sans-serif"'>Инструкция для работы с демо-версией раздела
«Заказ-проекты»<o:p></o:p></span></b></p>

<p class=MsoNoSpacing style='margin-top:18.0pt;margin-right:0cm;margin-bottom:
6.0pt;margin-left:0cm;text-align:justify;mso-outline-level:2'><b
style='mso-bidi-font-weight:normal'><span style='font-size:14.0pt;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-hansi-font-family:Calibri;
mso-hansi-theme-font:minor-latin;mso-bidi-font-family:Arial'>1. Ознакомление с перечнем
уже заведённых в раздел проектов<o:p></o:p></span></b></p>

<p class=MsoNoSpacing style='text-align:justify;text-indent:35.4pt'><span
style='font-family:"Arial","sans-serif"'>Проекты в окне представлены отдельными
строками, содержащими информацию:<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
наименования проектов;<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
даты внесения каждого из проектов в раздел;<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
персоналии, внёсшие каждый из проектов в раздел;<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
даты планируемых и реализованных этапов проекта. <o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify;text-indent:35.4pt'><span
style='font-family:"Arial","sans-serif"'>Для ознакомления с подробной
информацией о проекте, необходимо дважды кликнуть стрелкой мыши на его строку.<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify;text-indent:35.4pt'><span
style='font-family:"Arial","sans-serif"'>(Право ознакомления с подробной
информацией о проекте или редактирования проекта имеют только его участники
проекта, внесенные в описание проекта его инициатором или назначенный им
руководителем проекта -<span style='mso-spacerun:yes'>  </span>в Демо-версии
таких ограничений нет). <o:p></o:p></span></p>

<p class=MsoNoSpacing style='margin-top:6.0pt;margin-right:0cm;margin-bottom:
6.0pt;margin-left:0cm;text-align:justify;mso-outline-level:2'><b
style='mso-bidi-font-weight:normal'><span style='font-size:14.0pt;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-hansi-font-family:Calibri;
mso-hansi-theme-font:minor-latin;mso-bidi-font-family:Arial'>2. Заведение
нового проекта в раздел «Заказ-проекты»<o:p></o:p></span></b></p>

<p class=MsoNoSpacing style='margin-bottom:6.0pt;text-align:justify'><span
style='font-family:"Arial","sans-serif"'>1) <b style='mso-bidi-font-weight:
normal'>Нажать на значок «Список групп»</b>, расположенный в верхней левом
части окна раздела. <o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify;text-indent:35.4pt'><span
style='font-family:"Arial","sans-serif"'>Появляется поле «Список групп
проектов». В данном поле содержится список наименований групп, к одной из
которых может быть отнесен новый проект.<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify;text-indent:35.4pt'><span
style='font-family:"Arial","sans-serif"'>Если группы, к которой относится новый
проект, в списке нет, инициатор нового проекта может добавить данную группу:<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
нажать значок «Добавить»;<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
в открывшемся поле «Редактирование группы» вписать в строке «Наименование»
наименование новой группы и нажать кнопку «Сохранить»;<span
style='mso-spacerun:yes'>   </span><o:p></o:p></span></p>

<p class=MsoNoSpacing style='margin-bottom:6.0pt;text-align:justify'><span
style='font-family:"Arial","sans-serif"'>- в поле «Список новых проектов»
появилось внесённое наименование новой группы.<o:p></o:p></span></p>

<p class=MsoNoSpacing style='margin-bottom:6.0pt;text-align:justify'><span
style='font-family:"Arial","sans-serif"'>2) <b style='mso-bidi-font-weight:
normal'>Нажать на кнопку «Создать проект»</b>, расположенную в верхнем левом
углу.<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify;text-indent:35.4pt'><span
style='font-family:"Arial","sans-serif"'>В появившемся поле «Создание проекта»:<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
в строке «Группа» выбрать из выпадающего списка группу, к которой относится
проект. <o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
в строке «Имя» внести наименование нового проекта;<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
в поле автоматически фиксируется дата создания проекта;<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
в поле фиксируется ФИО инициатора проекта.<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
нажать на кнопку «Сохранить».<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify;text-indent:35.4pt'><span
style='font-family:"Arial","sans-serif"'>В окне раздела появилась строка нового
проекта.<o:p></o:p></span></p>

<p class=MsoNoSpacing style='margin-top:6.0pt;margin-right:0cm;margin-bottom:
6.0pt;margin-left:0cm;text-align:justify'><span style='font-family:"Arial","sans-serif"'>3)
<b style='mso-bidi-font-weight:normal'>Дважды кликнуть стрелкой мыши на строку
проекта</b>.<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify;text-indent:35.4pt'><span
style='font-family:"Arial","sans-serif"'>Открываются окна с информацией о
внутреннем содержании проекта:<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
«Описание».<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
«Конфигурация».<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
«План-факт».<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
«Участники проекта».<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
«Документация».<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
«Обсуждение».<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
«Оборудование и работы».<o:p></o:p></span></p>

<p class=MsoNoSpacing style='margin-top:6.0pt;margin-right:0cm;margin-bottom:
6.0pt;margin-left:0cm;text-align:justify'><span style='font-family:"Arial","sans-serif"'>4)
<b style='mso-bidi-font-weight:normal'>Заполнение окна «Описание»<o:p></o:p></b></span></p>

<p class=MsoNoSpacing style='text-align:justify;text-indent:35.4pt'><span
style='font-family:"Arial","sans-serif"'>В данное поле указывается ранее
выбранная группа проекта (строка «Группа») и наименование проекта (строка
«Наименование проекта»).<span style='mso-spacerun:yes'>  </span><o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify;text-indent:35.4pt'><span
style='font-family:"Arial","sans-serif"'>Заполняются строки «Название
заказчика», «Адрес объекта», «Назначение объекта», «Площадь объекта, м.кв.».<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify;text-indent:35.4pt'><span
style='font-family:"Arial","sans-serif"'>Может быть внесено описание проекта
(строка «Описание»).<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify;text-indent:35.4pt'><span
style='font-family:"Arial","sans-serif"'>Ставиться галочка на актуальном этапе
проекта (нижняя строка «Этапы проекта»).<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>Нажать
кнопку «Сохранить». <o:p></o:p></span></p>

<p class=MsoNoSpacing style='margin-top:6.0pt;margin-right:0cm;margin-bottom:
6.0pt;margin-left:0cm;text-align:justify'><span style='font-family:"Arial","sans-serif"'>5)
<b style='mso-bidi-font-weight:normal'>Заполнение окна «Конфигурация»<o:p></o:p></b></span></p>

<p class=MsoNoSpacing style='text-align:justify;text-indent:35.4pt'><span
style='font-family:"Arial","sans-serif"'>В данном окне галочками помечаются те
общие типы инженерных систем и услуг, которые предусматривает проект.<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify;text-indent:35.4pt'><span
style='font-family:"Arial","sans-serif"'>Нажать кнопку «Сохранить». <o:p></o:p></span></p>

<p class=MsoNoSpacing style='margin-top:6.0pt;margin-right:0cm;margin-bottom:
6.0pt;margin-left:0cm;text-align:justify'><span style='font-family:"Arial","sans-serif"'>6)
<b style='mso-bidi-font-weight:normal'>Заполнение окна «План-факт»<o:p></o:p></b></span></p>

<p class=MsoNoSpacing style='text-align:justify;text-indent:35.4pt'><span
style='font-family:"Arial","sans-serif"'>В данном окне ставятся плановые даты
основных этапов проекта: Подготовка, Согласование, Выполнение, Внедрение.<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify;text-indent:35.4pt'><span
style='font-family:"Arial","sans-serif"'>Нажать кнопку «Сохранить». <o:p></o:p></span></p>

<p class=MsoNoSpacing style='margin-top:6.0pt;margin-right:0cm;margin-bottom:
6.0pt;margin-left:0cm;text-align:justify'><span style='font-family:"Arial","sans-serif"'>7)
<b style='mso-bidi-font-weight:normal'>Заполнение окна «Участники проекта»<o:p></o:p></b></span></p>

<p class=MsoNoSpacing style='text-align:justify;text-indent:35.4pt'><span
style='font-family:"Arial","sans-serif"'>Для внесения нового участника проекта:<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
нажать на кнопку (слева вверху) «Добавить участника»;<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
в выпадающем списке выбрать тип участника;<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
в появившемся поле «Добавить участника» в выпадающем списке возможных участников
проекта (из числа имеющихся на Портале специалистов) и нажать кнопу «Добавить»;<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify;text-indent:35.4pt'><span
style='font-family:"Arial","sans-serif"'>В появившейся строке нового участника
проекта содержится информация об участнике: ФИО, город, страна.<o:p></o:p></span></p>

<p class=MsoNoSpacing style='margin-top:6.0pt;margin-right:0cm;margin-bottom:
6.0pt;margin-left:0cm;text-align:justify'><span style='font-family:"Arial","sans-serif"'>8)
<b style='mso-bidi-font-weight:normal'>Заполнение окна «Документация»<o:p></o:p></b></span></p>

<p class=MsoNoSpacing style='text-align:justify;text-indent:35.4pt'><span
style='font-family:"Arial","sans-serif"'>Чтобы внести новый документ проекта
необходимо: <o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
Нажать кнопку «Типы документов» и в открывшемся поле «Список групп документов»
проверить, есть ли там в списке тип документа, соответствующий загружаемому.<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
Если нужно добавить тип документа» - нажать в поле «Список групп документов»
кнопку «Добавить». Затем в открывшемся поле «Редактирование группы» внести
наименование новой группы и нажать на кнопку «Сохранить».<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
Если необходимо отредактировать наименование группы в поле «Список групп
документов» - нажать на зелёный значок справа от строки и в открывшемся поле
«Редактирование группы» провести изменения наименования. Затем нажать в поле
кнопку «Сохранить».<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
Теперь можно начать присоединять документ. Для этого нажать на кнопку «Добавить
документ». В открывшемся поле «Создание документа» в строке «Тип документа»
выбрать из выпадающего списка соответствующее наименование. Вписать имя
документа, которое будет отражено в разделе. <o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
Затем нажать на кнопку «Сохранить и загрузить файл». Открывается поле «Передача
фалов на сервер». В нём нужно нажать папку «Открыть» - оказывается на рабочем
столе компьютера. Выделяем нужный файл и нажимаем кнопку «Открыть». В поле
«Передача фалов на сервер» возникает строка с наименованием выбранного файла.<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
Ставим галочку слева от данного файла и нажимаем в верхнем меню поля кнопу
«Загрузить».<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
Данный файл с новым именем, указанным в поле «Создание документа», размещается
строкой в окне документация.<span style='mso-spacerun:yes'>  </span><o:p></o:p></span></p>

<p class=MsoNoSpacing style='margin-top:6.0pt;margin-right:0cm;margin-bottom:
6.0pt;margin-left:0cm;text-align:justify'><span style='font-family:"Arial","sans-serif"'>9)
<b style='mso-bidi-font-weight:normal'>Работа в окне «Обсуждение»<o:p></o:p></b></span></p>

<p class=MsoNoSpacing style='text-align:justify;text-indent:35.4pt'><span
style='font-family:"Arial","sans-serif"'>В нижней части открывшегося поля
(слева от кнопки «Комментировать») размещаем комментарий, касающийся любого
аспекта проекта. Нажимаем кнопку «Ко<a name="_GoBack"></a>мментировать». В
верхней части окна появляется данный комментарий с ФИО автора, доступный
просмотру участников проекта.<o:p></o:p></span></p>

<p class=MsoNoSpacing style='margin-top:6.0pt;margin-right:0cm;margin-bottom:
6.0pt;margin-left:0cm;text-align:justify'><span style='font-family:"Arial","sans-serif"'>10)
<b style='mso-bidi-font-weight:normal'>Работа в окне «Оборудование и работы»<o:p></o:p></b></span></p>

<p class=MsoNoSpacing style='text-align:justify;text-indent:35.4pt'><span
style='font-family:"Arial","sans-serif"'>В данном окне создается спецификация
оборудования и работ проекта.<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify;text-indent:35.4pt'><span
style='font-family:"Arial","sans-serif"'>В окне есть два поля: <o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
верхнее – «Оборудование» - для составления спецификации необходимого
оборудования проекта и сопутствующих конкретному оборудованию услуг;<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
нижнее<span style='mso-spacerun:yes'>  </span>- «Специальные услуги» - для
составления спецификации необходимых в проекте специальных услуг и необходимых
для их реализации инструментов.<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify;text-indent:35.4pt'><span
style='font-family:"Arial","sans-serif"'>Для добавления номенклатурной позиции
в поле «Оборудование» необходимо:<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
в окне проекта нажать на кнопку «Добавить», после чего пользователь входит в
поле «Добавление в конфигурацию», в котором содержится копия каталогов из
раздела Портала: «Товары и услуги»;<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
выбрать в левом списке типов оборудования необходимый тип – нажать стрелкой
мыши;<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
в правом поле «Результаты выборки» появляется список оборудования данного типа,
имеющегося в каталогах Портала;<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
посредством фильтров – в поле «Фильтры» в каталогах находится необходимая номенклатура;<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
данная номенклатура выделяется, после чего нажимается кнопка (нижний правый
угол) «Добавить в конфигурацию».<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
в окне проекта появилась новая номенклатурная строка, соответствующая по цене и
характеристикам выбранной в каталоге строке.<o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify'><span style='font-family:"Arial","sans-serif"'>-
те же действия проводятся для загрузки из соответствующих каталогов специальных
услуг. <o:p></o:p></span></p>

<p class=MsoNoSpacing style='text-align:justify;text-indent:35.4pt'><span
style='font-family:"Arial","sans-serif"'>В полосе, расположенной на краю окна
проекта автоматически размещаются: общие суммы по разделам (оборудование,
услуги, специальные услуги, материалы), а также итоговая сумма по проекту. <o:p></o:p></span></p>