<? if($this->success) { ?>
    <div align="center">
        <div style="color:green; text-align:center;">
            <?=$this->message?>
        </div>
    </div>
    <script type="text/javascript">
        setTimeout("document.location.href='/'", 5000);
    </script>
<? } else { ?>
    <div align="center">
        <div style="color:red; text-align:center;">
            <?=$this->message?>
        </div>
    </div>
<? } ?>