<h1>Absent files count: <?=$this->count?></h1>
<table cellspacing="0" cellpadding="5" border="1">
    <thead>
        <td><b>ID</b></td>
        <td><b>Path</b></td>
        <td><b>Date</b></td>
        <td><b>Name</b></td>
        <td><b>Account ID</b></td>
    </thead>
    <?php foreach ($this->data as $row):?>
        <tr>
            <td><?=$row['id']?></td>
            <td><?=$row['path']?></td>
            <td><?=$row['date']?></td>
            <td><?=$row['name']?></td>
            <td><?=$row['account_id']?></td>
        </tr>
    <?php endforeach;?>
</table>