<h1>Количество пустых документов: <?=$this->count?></h1>
<table cellspacing="0" cellpadding="5" border="1">
    <thead>
        <td><b>ID</b></td>
        <td><b>Имя документа</b></td>
        <td><b>Тип документа</b></td>
        <td><b>Проект</b></td>
        <td><b>Группа проекта</b></td>
        <td><b>Дата создания проекта</b></td>
    </thead>
    <?php foreach ($this->data as $row):?>
        <tr>
            <td><?=$row['id']?></td>
            <td><?=$row['name']?></td>
            <td><?=$row['doc_type']?></td>
            <td><?=$row['project_name']?></td>
            <td><?=$row['project_group']?></td>
            <td><?=$row['created_date']?></td>
        </tr>
    <?php endforeach;?>
</table>
<br/><br/><br/>
<?php 
foreach ($this->data as $row) {
    echo $row['id'] . ', ';
}
?>