Ext.ns('xlib.System');

xlib.System = function() {
    var types = <?=Zend_Json::encode($this->messageTypes); ?> || [];
    return {
        getMessageTypes: function() {
            return types;
        }
    };
}();

Ext.ns('xlib.Acl');

xlib.Acl.Storage = function() {

    var permissions = <?=Zend_Json::encode($this->acl); ?> || [];
    var resources = <?=Zend_Json::encode($this->resources); ?> || {};
    var privileges = <?=Zend_Json::encode($this->privileges); ?> || {};
    var identity = <?=Zend_Json::encode($this->identity); ?> || {};

    return {
        getPermissions: function() {
            return permissions;
        },

        getResources: function() {
            return resources;
        },

        getPrivileges: function() {
            return privileges;
        },

        getIdentity: function() {
            return identity;
        }
    };
}();
