if ('object' != typeof Admin) {
    Admin = {};
}

if ('object' != typeof Admin.Acl) {
    Admin.Acl = {};
}

Admin.Acl.Storage = function() {

    var permissions = <?=Zend_Json::encode($this->acl); ?> || [];
    var resources = <?=Zend_Json::encode($this->resources); ?> || {};
    var privileges = <?=Zend_Json::encode($this->privileges); ?> || {};

    return {
        getPermissions: function() {
            return permissions;
        },

        getResources: function() {
            return resources;
        },

        getPrivileges: function() {
            return privileges;
        }
    };
}();