<div style="margin:50px auto; width:220px;">
    <center>
        <a href="http://e-head.ru">
            <img src="/images/eurasclimat-logo-big.png"  style="border:none;"/>
        </a>
    </center>
    <br /><br />
    <div style="color:red; text-align:right;">
        <?=$this->message?>
    </div>
    <form action="/index/login" method="post">
        <input type="hidden" name="do" value="login"/>
        <table cellpadding="5" cellspacing="0" border="0">
            <tr>
                <td>Логин:</td>
                <td><input type="text" name="login" style="width:150px;"/></td>
            </tr>
            <tr>
                <td>Пароль:</td>
                <td><input type="password" name="password" style="width:150px;"/></td>
            </tr>
            <tr align="right">
                <td colspan="2"><input type="submit" value="Войти"/></td>
            </tr>
        </table>
    </form>
</div>