<div align="center">
    <div style="color:red; text-align:right;">
        <?=$this->message?>
    </div>
    <form action="/index/login" method="post" id="main-login-form">
        <input type="hidden" name="do" value="login"/>
        логин
        <br/>
        <input type="text" name="login"/>
        <br/>
        пароль<br/>
        <input type="password" name="password"/>
        <br/><br/>
        <input type="submit" value="Войти" style="width: 95px;" />
        <input type="button" disabled="disabled" value="Регистрация" style="width: 105px;" />
    </form>
</div>