<div align="center">
    <div style="color:red; text-align:center;">
        <?=$this->message?>
    </div>
    <form action="/index/auth" method="post" id="main-login-form">
        <input type="hidden" name="do" value="login"/>
        логин
        <br/>
        <input type="text" name="login"/>
        <br/>
        пароль<br/>
        <input type="password" name="password"/>
        <br/><br/>
        <input type="submit" value="Войти" style="width: 95px;" />
<!--        <br/><br/><a href="/">Гостевой вход</a> | <a href="/">Регистрация</a>-->
    </form>
</div>