SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `manufacturers`;
CREATE TABLE IF NOT EXISTS `manufacturers` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(256) DEFAULT NULL,
  `type` varchar(256) DEFAULT NULL,
  `url` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=59 ;

INSERT INTO `manufacturers` (`id`, `name`, `type`, `url`) VALUES
(1, 'Mitsubishi Electric', 'Кондиционирование, отопление, вентиляция', 'http://www.mitsubishi-aircon.ru'),
(2, 'Daikin', 'Кондиционирование, отопление, вентиляция', 'http://www.daikin.ru/'),
(3, 'Panasonic', 'Кондиционирование', 'http://www.panasonic.ru/'),
(4, 'General climate ', 'Кондиционирование, вентиляция, отопление', 'http://generalclimate.ru/'),
(5, 'Lessar', 'Кондиционирование, вентиляция', 'http://lessar.ru/'),
(6, 'Ballu', 'Кондиционирование, отопление', 'http://www.ballu.ru/'),
(7, 'Carrier', 'Кондиционирование, вентиляция', 'http://www.carrier-russia.ru/'),
(8, 'Danfoss', 'Отопление, автоматика', 'http://ic.danfoss.ru/'),
(9, 'GEA Klimatechnika', 'Кондиционирование, вентиляция, отопление', 'http://www.geagkm.ru/'),
(10, 'Арктика', 'Вентиляция', 'http://arktika.ru/'),
(11, 'NED', 'Вентиляция, автоматизация', 'http://air-ned.com/ '),
(12, 'SistemAir', 'Вентиляция', 'http://www.systemair.com/ru/Russia/'),
(13, 'Ostberg', 'Вентиляция', 'http://osberg-russia.ru/'),
(14, 'Remak', 'Вентиляция', 'http://www.remak-moscow.ru/'),
(15, 'Meibes', 'Отопление, автоматика', 'http://meibes.ru/'),
(16, 'KOFULSO', 'Трубы', 'http://www.kofulso-olton.ru/techdocs/instruction/'),
(17, 'Imp Klima', 'Отопление', 'http://imp-klima.ru/'),
(18, 'REHAU', 'Водоснабжение, отопление, окна', 'http://www.rehau.com/RU_ru/'),
(19, 'TECE', 'Водоснабжение, канализация', 'http://www.tece.ru/ru'),
(20, 'KAN-therm', 'Водоснабжение', 'http://ru.kan-therm.com/'),
(21, 'Cupori Oy', 'Водоснабжение, отопление', 'http://www.cupori.com/ru'),
(22, 'WIELAND SANCO', 'Трубы', 'http://www.wieland.ru'),
(23, 'Alurad', 'Отопление, водоснабжение', 'http://www.alurad.ru/'),
(24, 'Global radiatori', 'Отопление', 'http://globalradiator.ru/'),
(25, 'Sira', 'Отопление', 'http://www.siragroup.it/ru'),
(26, 'JAGA', 'Отопление', 'http://www.jaga-design.ru/'),
(27, 'VARMANN', 'Отопление', 'http://he.varmann.ru/'),
(28, 'MINIB', 'Отопление', 'http://minib.msk.ru'),
(29, 'Mohlenhoff', 'Отопление, охлаждение', 'http://www.mohlenhoff.ru/'),
(30, 'Zehnder', 'Отопление', 'http://zehnder.su/contacts/'),
(31, 'Korado', 'Отопление', 'http://www.korado.ru/'),
(32, 'Конрад', 'Отопление', 'http://www.konrad-group.ru/'),
(33, 'Arbonia', 'Отопление, водоснабжение', 'http://www.arbonia.su/'),
(34, 'Dia Norm', 'Отопление', 'http://www.dia-norm.ru/about/'),
(35, 'ABB', 'Электрика', 'http://www.abb.ru/'),
(36, 'Schneider Electric', 'Электрика', 'http://www.schneider-electric.ru'),
(37, 'GIERSCH', 'Отопление', 'http://www.giersch.ru/'),
(38, 'Kermi', 'Отопление, водоснабжение', 'http://www.kermi.ru/'),
(39, 'KAMPMANN', 'Отопление, охлаждение, вентиляция', 'http://www.kampmann.ru/'),
(40, 'Viega', 'Водоснабжение, канализация', 'http://www.viega.ru/'),
(41, 'REFLEX', 'Отопление, охлаждение', 'http://www.reflex-rus.ru/'),
(42, 'ВЕЗА', 'Кондиционирование, вентиляция', 'http://www.veza.ru/'),
(43, 'Маммут Климат', 'Кондиционирование, вентиляция, отопление', 'http://www.mammoth-russia.ru/'),
(44, 'Varmann', 'Отопление', 'http://varmann.ru/'),
(45, 'KTK KLIMATECHNIK', 'Кондиционирование', 'http://www.ktk.it/'),
(46, 'EDPAC', 'Кондиционирование', 'http://www.edpac.com/'),
(47, 'STULZ', 'Кондиционирование', 'http://www.stulz-air.ru/'),
(48, 'AL-KO', 'Кондиционирование, вентиляция', 'http://www.al-ko.com.ru/'),
(49, 'DANTEX', 'Кондиционирование, вентиляция', 'http://dantex.ru/'),
(50, 'MASEnergo Group', 'Кондиционирование, автоматика', 'http://www.liebert-masenergo.ru/'),
(51, 'Uniflair', 'Кондиционирование', 'http://uniflair.ru/'),
(52, 'APC', 'Электрика', 'http://www.apc.com/'),
(53, 'Rittal', 'Кондиционирование, электрика', 'http://www.rittal.com/'),
(54, 'ZPAS', 'Телекоммуникации, электрика', 'http://www.zpas.ru/'),
(55, 'CONTEG', 'Телекоммуникации', 'http://www.conteg.ru/'),
(56, 'АЕСП', 'Телекоммуникации', 'http://www.aesp.ru/'),
(57, 'TLK', 'Телекоммуникации', 'http://www.tlk-rc.ru/'),
(58, 'DELL', 'Телекоммуникации', 'http://www.dell.ru/');

SET FOREIGN_KEY_CHECKS=1;