<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <link rel="shortcut icon" href="<?=$this->baseUrl(); ?>/images/favicon.ico" type="image/x-icon" />
        <link rel="icon" href="<?=$this->baseUrl(); ?>/images/favicon.png" type="image/png" />
        <link rel="stylesheet" type="text/css" href="/main.css">
    </head>
    <body>
        <?=$this->layout()->content; ?>
    </body>
</html>