<!DOCTYPE html>
<html lang="ru">
    <head>
        <title>ЕВРАЗКЛИМАТ - Центр инженерных систем и технологий</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="X-UA-Compatible" content="chrome=1">

        <link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon" />
        <link rel="icon" href="/images/favicon.png" type="image/png" />

        <link rel="stylesheet" type="text/css" href="/library/ext4/resources/css/ext-all.css">

        <link rel="stylesheet" type="text/css" href="/icons.css">

        <link rel="stylesheet" type="text/css" href="/main.css">

        <script type="text/javascript" src="/library/ext4/ext-all.js"></script>

        <script type="text/javascript" src="/library/ext4/ext-lang-ru.js"></script>

        <script type="text/javascript" src="/start.js"></script>
    </head>
    <body>

        <div id="bg-top">‌</div>
        <div id="bg-bottom">‌</div>

        <div id="bg-tl">‌</div>
        <div id="bg-bl">‌</div>
        <div id="bg-tr">‌</div>
        <div id="bg-br">‌</div>

        <?php echo $this->layout()->content; ?>

    </body>
</html>