<!DOCTYPE html>
<html lang="ru">
    <head>
        <link rel="stylesheet" type="text/css" href="/library/ext4/resources/css/ext-all.css">
        <link rel="stylesheet" type="text/css" href="/icons.css">
        <link rel="stylesheet" type="text/css" href="/main.css">
        <link rel="stylesheet" type="text/css" href="/images-view.css">
        <link rel="stylesheet" type="text/css" href="/library/xlib/upload/css/upload.css">
        <title>Корпоративный портал ОАО "Евразклимат"</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="X-UA-Compatible" content="chrome=1">
        <meta name="google-site-verification" content="nsi8YDDju9uU2ZrHAPEmevqCCNGDHINql8GNipP6Jo4" />
        <meta name='yandex-verification' content='6960c79405963a67' />
        <meta name="description" content="ОАО «Евразклимат» предоставляет услуги по реализации проектов в сфере строительства внутренних и внешних инженерных систем, сетей и технологий, как в комплексе, так и отдельными этапами, такими как проектирование, логистика, снабжение, комплектация объектов инженерной продукцией и материалами, производство нестандартного оборудования и изделий, разработка и производство электро-щитового оборудования, строительно-монтажные работы, технический надзор, разработка, утверждение и контроль исполнения графиков производства, организация выполнения шеф-монтажных и пуско-наладочных работ, гарантийное и пост гарантийное (сервисное) обслуживание"/>
        <meta name="keywords" content="Механические системы, отопление, вентиляция, кондиционирование, водоснабжение, канализация, системы пожаротушения, электротехнические системы,системы электроснабжения,системы освещения,слаботочные системы, сигнализация, системы безопасности и наблюдения, контроль доступа, автоматизация систем отопления, вентиляции и кондиционирования, систем водоснабжения и канализации,контроля и управления доступом, газоснабжения,системы чистых помещений, пищевые технологии, холодильное оборудование, технологическое оборудование, торговая мебель, весовое оборудование"/>
        <link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon" />
        <link rel="icon" href="/images/favicon.png" type="image/png" />

    </head>
    <body>

        <div id="bg-top">‌</div>
        <div id="bg-bottom">‌</div>
        <div id="bg-tl">‌</div>
        <div id="bg-bl"></div>
        <div id="bg-tr">‌</div>
        <div id="bg-br">‌</div>

        <?php echo $this->layout()->content; ?>

        <script type="text/javascript" src="/library/ext4/ext-all.js"></script>
        <!--
        <script type="text/javascript" src="/library/ext4/ext.js"></script>
        <script type="text/javascript" src="/library/ext4/ext-all-debug.js"></script>
        -->

        <script type="text/javascript" src="/library/ext4/ext-lang-ru.js"></script>

<!--        <script type="text/javascript" src="/default/index/get-permissions"></script>-->
        <script type="text/javascript" src="/default/index/get-system-settings"></script>

        <script type="text/javascript" src="/start.js"></script>
    </body>
</html>